### ISSUE TITLE
Dataset Processing

### ISSUE THREAD

**Issue by jodie-kang** [nju-websoft/SCR#1]
Could you please provide the code of data processing? Many thanks!

**Comment by jodie-kang** [comment]
MAVEN is a public data set, is it convenient for you to provide the data set after this part of processing?

**Comment by njuwzt** [comment]
Sure, you can obtain the MAVEN dataset after processing through this link: https://drive.google.com/file/d/1-Zud2K_X0cmffwXAMBZ_WwNd9u88vHEE/view?usp=drive_link. Thanks!
