### ISSUE TITLE
模型训练问题请教

### ISSUE THREAD

**Issue by jqianaaaa** [nju-websoft/SCR#3]
您好，我在使用您的代码进行maven数据集进行模型训练时，经常出现下图所示的问题，请问这是什么原因呢？
![图片1](https://github.com/nju-websoft/SCR/assets/156065335/d2049ca3-1284-4f71-8f30-1716c7494d2d)

**Comment by njuwzt** [comment]
您好，报错信息显示应该是显卡显存不足。
